added allowed_number_requests to mock
nikitanovosibirsk/jj pull request #30
Opened 2022-03-11 19:41 UTC by TeoDV

**Какая выбрана реализация для проблемы с ретраями моков**
Из 3-х вариантов реализации задачи https://github.com/nikitanovosibirsk/veps/issues/17 выбран последний.

- Первый вариант нахожу неудобным применительно к нашей архитектуре проектов. Сейчас мы создаем разные моки с одним и тем же матчером, но разными респонсами. Если появится очередь моков, то придется дублировать тело ответа для новой сущности (MockedResponseQueue) или как-то его выносить в переменные (затруднит чтение), чтобы использовать и в обычных моках, и в моках с очередью. Именовать готовые моки с очередью тоже проблематично: mocked_queue_auth_user_token_info_500_500_200 - не очень изящно.
- Второй вариант отсекла в большей степени по причине отсутствия понимания, что важно проверять в тестах со статистическими “выбросами”. Рассматривала бы отдельно, так как требует погружения в суть вопроса, да и реализация, полагаю, не самая тривиальная выходит.
- Третий вариант мне понравился тем, что мы будем использовать наши моки, как обычно. Потребуется только пробросить дополнительный параметр, изменяющий поведение мока.

**Что сделано**
Добавлена переменная allowed_number_requests, в которую можно передать количество допустимых запросов на текущий мок. 
- Если allowed_number_requests > 0, то мы попадем в мок.
- Если allowed_number_requests == 0, то мы уже исчерпали допустимое кол-во запросов на этот мок, а, значит, мы этот хендлер из выборки пропустим.
- Если allowed_number_requests is None, то мы не передали ограничение на кол-во допустимых запросов, а, значит, этот хендлер будет рабочим всегда (сюда же входят случаи запросов на register/deregister хендлеров).
- Не обработан случай allowed_number_requests < 0, так как не увидела, чтобы валидировались переменные передаваемые в мок. По-хорошему, стоит добавить, но тут встают вопросы: каким способом возвращать ошибку, и куда эту валидацию положить?

Добавлен файлик  `start_client_with_different_mock_responses.py` для быстрой проверки на текущий момент обсуждения.

Не уверена, что правильно всё сделала как относительно задумки, так и устройства кода, но хотя бы подразобралась, как реализована библиотека jj.

Пока не стала трогать реализацию ExpireAfterXSeconds, так как плохо могу представить, как эту логику можно реализовать.

2022-03-16 18:17 UTC, nikitanovosibirsk commented
Направление верное, осталось обобщить решение и проверить на нескольких реализациях.

Например:

```python
class ExpirationPolicy:
    def is_expired(handler) -> bool:
        raise NotImplementedError()

class ExpireNever(ExpirationPolicy):  # default
    def is_expired(handler) -> bool:
        return False

class ExpireAfterRequests(ExpirationPolicy):
    def __init__(self, /, requests: int) -> None:
        self._cur_requests = 0
        self._max_requests = requests

    def is_expired(self, handler) -> bool:
        if self._cur_requests < self._max_requests:
            self._cur_requests += 1
            return False
        return True

class ExpireAfterTime(ExpirationPolicy):
    def __init__(self, /, time: float) -> None:
        self._max_time = time

    def is_expired(self, handler) -> bool:
        if time() < self._max_time:
            return False
        return True
```

Тогда можно будет задавать любую политику для конкретной связки matcher-handler:

```python
matcher = jj.match("POST", "/users")
response = jj.Response(status=200, json=[])
policy = ExpireAfterRequests(3)

async with mocked(matcher, response, expiration_policy=policy) as mock:
    pass
```

2022-03-16 18:17 UTC, nikitanovosibirsk commented
Кстати, видимо эта штука заменит флаг `disposable`

2022-03-22 13:40 UTC, nikitanovosibirsk requested changes

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/mock/_remote_mock.py
> +            expiration_policy = ExpireNever()
Можно убрать, так как внутри RemoteHandler применится дефолт

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/mock/_remote_handler.py
> +            return ExpireNever()
Давай в конструктор утащим, а тут будет просто геттер

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/mock/_mock.py
> +        assert isinstance(expiration_policy, (ExpireNever, ExpireAfterRequests))
```
assert isinstance(expiration_policy, ExpirationPolicyType)
```

Иначе нельзя будет кастомные создавать

2022-03-22 13:40 UTC, nikitanovosibirsk commented on examples/custom_matcher/start_client_with_different_mock_responses.py
> +                while requests_count > 0:
```
for _ in range(requests_count):
```

2022-03-22 13:40 UTC, nikitanovosibirsk commented on examples/custom_matcher/start_client_with_different_mock_responses.py
> +import asyncio
Перенеси пример в `./examples/expiration_policy`

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expire_never.py
> +    def __packed__(self) -> Dict:  # type: ignore
Почему тут `type: ignore`?

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expire_never.py
> +class ExpireNever(ExpirationPolicy):  # default
```suggestion
class ExpireNever(ExpirationPolicy):
```

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expire_never.py
> +class ExpireNever(ExpirationPolicy):  # default
Дефолтная это политика или нет — решается на более высоком уровне

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expire_after_requests.py
> +    def __unpacked__(cls, max_requests_count: int) -> "ExpireAfterRequests":
`__unpacked__` лучше вот так декларировать:

```
def __unpacked__(cls, *, max_requests_count: int, **kwargs: Any) -> "ExpireAfterRequests":
```

Тогда можно будет расширять без поломки обратной совместимости

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/resolvers/_resolver.py
> +    def _is_expired_request(self, handler: HandlerFunction) -> bool:
Лучше `_is_handler_expired`, так как протухает обработчик, а не запрос

2022-03-22 13:40 UTC, nikitanovosibirsk commented on jj/expiration_policy/__init__.py
> +from typing import Union
Всю папку наверное лучше в `jj/mock/expiration_policy` положить, так как это работает только для remote-мока

2022-03-22 13:52 UTC, nikitanovosibirsk commented on jj/mock/_mock.py
> +        assert isinstance(expiration_policy, (ExpireNever, ExpireAfterRequests))
Тут ещё `None` может быть, если клиент использует новую версию, а сервер старую

2022-03-22 14:06 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expiration_policy.py
> +    def is_expired(self) -> bool:
Давай сделаем такой интерфейс:

```
async def is_expired(self, request: Request) -> bool:
```

Сейчас можно использовать данные только из глобального скоупа, это ограничивает применение

Например, нельзя написать политику, которая экспайрится после того, как пришёл определённый параметр в query/headers.

А чтобы достать какие-то данные из тела запроса, нужно его прочитать:
```
await request.post()
```

2022-03-22 14:06 UTC, nikitanovosibirsk commented
По тестам:

- Давай отдельно проверим ExpireAfterRequests, включая packed/unpacked
- Интеграционно с дефолтной политикой и с ExpireAfterRequests
- Плюс получении history после протухания хендлера

Вот тут примеры есть https://github.com/nikitanovosibirsk/jj/tree/master/tests/mock

2022-03-22 19:06 UTC, TeoDV commented on jj/expiration_policy/_expire_never.py
> +class ExpireNever(ExpirationPolicy):  # default
Случайно твой комментарий захватила из примера. Убрано

2022-03-22 19:06 UTC, TeoDV commented on jj/expiration_policy/_expire_never.py
> +    def __packed__(self) -> Dict:  # type: ignore
Не понимаю, как полечить ошибку 
```python
error:(B Missing type parameters for generic type (B"Dict"(B(B
```

2022-03-23 07:18 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expire_never.py
> +    def __packed__(self) -> Dict:  # type: ignore
`Dict` — generic type, надо указать типы параметров, в данном случае `Dict[str, Any]`

2022-03-27 20:28 UTC, TeoDV commented on jj/mock/_mock.py
> +        assert isinstance(expiration_policy, (ExpireNever, ExpireAfterRequests))
> если сервер использует новую версию, а клиент старую

Как это работает? 
Мол, с docker-hub берется новая сборка, а в requirements установлена устаревшая версия jj?

А что в таком случае должно подставляться? ExpireNever?

2022-03-27 20:41 UTC, TeoDV commented on jj/expiration_policy/__init__.py
> +from typing import Union
У меня никак не получается перенести, так как импорты циклятся:
```python
Traceback (most recent call last):
  File "examples/expiration_policy/start_server.py", line 1, in <module>
    import jj
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/__init__.py", line 1, in <module>
    from ._core import (
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/_core.py", line 7, in <module>
    from .apps import AbstractApp, BaseApp, DefaultApp
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/apps/__init__.py", line 2, in <module>
    from ._base_app import BaseApp, create_app, define_app
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/apps/_base_app.py", line 5, in <module>
    from ..resolvers import Resolver
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/resolvers/__init__.py", line 3, in <module>
    from ._resolver import Resolver
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/resolvers/_resolver.py", line 5, in <module>
    from jj.mock.expiration_policy import ExpirationPolicy
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/mock/__init__.py", line 7, in <module>
    from jj.matchers import LogicalMatcher, RequestMatcher
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/matchers/__init__.py", line 3, in <module>
    from ._resolvable_matcher import ResolvableMatcher
  File "/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/matchers/_resolvable_matcher.py", line 3, in <module>
    from ..resolvers import Resolver
ImportError: cannot import name 'Resolver' from partially initialized module 'jj.resolvers' (most likely due to a circular import) (/home/dv/dev/jj/.venv/lib/python3.8/site-packages/jj/resolvers/__init__.py)
```
Нет идей, как подвигать или как возможно ограничить вызов импортов для Resolver, чтобы заработало.

2022-03-27 22:48 UTC, TeoDV commented
> По тестам:
> 
> * Давай отдельно проверим ExpireAfterRequests, включая packed/unpacked
> * Интеграционно с дефолтной политикой и с ExpireAfterRequests
> * Плюс получении history после протухания хендлера
> 
> Вот тут примеры есть https://github.com/nikitanovosibirsk/jj/tree/master/tests/mock

1. Не поняла про packed/unpacked, так как мы в любом случае зарегистрируем хендлер, а, значит, и вызовем эти методы. Или их нужно как-то отдельно вызвать? Если да, то что должно быть в assert для packed?
2. Добавила:
- для None не проверяла, так как это покроется тестами для мока. 
- для ExpireAfterRequests добавила кейсы с дерегистрацией с реквестом и без него по аналогии с тестами для мока.

3. Добавила один тест с историей. По идее одного же достаточно на один метод?

2022-03-28 12:16 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expire_after_requests.py
> +        self.max_requests_count = max_requests_count
Давай сделаем protected, чтобы не было соблазна после создания менять

```
self._max_requests_count = max_requests_count
```

2022-03-28 12:16 UTC, nikitanovosibirsk commented on tests/expiration_policy/test_expire_after_requests.py
> +        expiration_policy = ExpireAfterRequests(count_requests)
Может ассерт добавить в конструктор?

2022-03-28 12:16 UTC, nikitanovosibirsk commented on tests/expiration_policy/test_expiration_policy_history.py
> +            for i in range(2):
Тут самое интересное проверить после 3 запроса

2022-03-28 12:16 UTC, nikitanovosibirsk commented on jj/expiration_policy/__init__.py
> +from typing import Union
Не заметил, что Resolver тоже зависит от ExpirationPolicy. Так как резолвер в корне, пусть и expiration_policy будет в корне

2022-03-28 12:16 UTC, nikitanovosibirsk commented on jj/expiration_policy/_expiration_policy.py
> +    def is_expired(self) -> bool:
up

2022-03-28 12:17 UTC, nikitanovosibirsk requested changes
...

2022-03-28 12:36 UTC, nikitanovosibirsk commented on jj/mock/_mock.py
> +        assert isinstance(expiration_policy, (ExpireNever, ExpireAfterRequests))
Тут два кейса может быть:

1. Новая версия сервера, старая версия клиента (например, обновили только образ)

 В этом случае клиент не передаст exp_policy, а значит сервер должен уметь это обрабатывать:

```python
expiration_policy = decoded.get("expiration_policy", None)
assert isinstance(expiration_policy, ExpirationPolicy)
```

2. Старая версия севера, новая версия клиента (например, обновили только requirements.txt)

В этом случае клиент не должен передавать того, о чём ещё не знает сервер. А значит придётся всё-таки сделать по дефолту expiration_policy=None, а не ExpireNever

2022-04-03 09:51 UTC, nikitanovosibirsk commented
👍

2022-04-03 09:51 UTC, merged